version: '3.8'

networks:
  own_network:
    driver: bridge

volumes:
  mariadb:
    driver_opts:
      type: none
      device: /home/florian/data/mariadb
      o: bind
  wordpress:
    driver_opts:
      type: none
      device: /home/florian/data/wordpress
      o: bind

services:
  own_mariadb:
    container_name: mariadb
    image: mariadb
    env_file: .env
    build:
      context: ./requirements/mariadb
      args:
        - DB_DB=${DB_DB}
        - DB_USER=${DB_USER}
        - DB_PW=${DB_PW}
        - DB_ROOT_PW=${DB_ROOT_PW}
    restart: on-failure
    volumes:
      - mariadb:/var/lib/mysql:rw
    networks:
      - own_network

  own_wordpress:
    container_name: wordpress
    image: wordpress
    env_file: .env
    build: ./requirements/wordpress
    restart: on-failure
    volumes:
      - wordpress:/var/www/wordpress:rw
    networks:
      - own_network
    depends_on:
      - own_mariadb

  own_nginx:
    container_name: nginx
    image: nginx
    build: ./requirements/nginx
    restart: on-failure
    volumes:
      - wordpress:/var/www/wordpress:rw
    networks:
      - own_network
    ports:
      - "443:443"
    depends_on:
      - own_wordpress

