USE mysql;

DELETE FROM user WHERE user='';
DROP DATABASE IF EXISTS test;

ALTER USER 'root'@'localhost' IDENTIFIED BY 'DB_ROOT_PW';
CREATE OR REPLACE USER 'DB_USER' IDENTIFIED BY 'DB_PW';

CREATE DATABASE IF NOT EXISTS DB_DB;
GRANT ALL PRIVILEGES ON DB_DB.* TO 'DB_USER';
FLUSH PRIVILEGES;
