USE mysql;

DELETE FROM user WHERE user='';
DROP DATABASE IF EXISTS test;

ALTER USER 'root'@'localhost' IDENTIFIED BY 'DB_ROOT_PW';
CREATE OR REPLACE USER 'DB_USER_NAME' IDENTIFIED BY 'DB_USER_PW';

CREATE DATABASE IF NOT EXISTS DB_NAME;
GRANT ALL PRIVILEGES ON DB_NAME.* TO 'DB_USER_NAME';
FLUSH PRIVILEGES;
