CREATE DATABASE IF NOT EXISTS DB_DB;
ALTER USER 'root'@localhost IDENTIFIED BY 'DB_ROOT_PW';
CREATE USER 'DB_USER' IDENTIFIED BY 'DB_PW';
GRANT ALL PRIVILEGES ON DB_DB.* TO 'DB_USER';
FLUSH PRIVILEGES;
